import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import { GoogleAnalytics } from '@next/third-parties/google'
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SurveyJS + NextJS Quickstart Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gaTagId = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID ||'G-9WHD1HB8XC'

  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
      <GoogleAnalytics gaId={gaTagId} />

    </html>
  );
}
